#!/bin/bash
set -euo pipefail

# NOTE: DO NOT DEFINE ENV VARS TO SHARE DATA ACROSS WORKFLOW STEPS IN THIS DIR. IT MUST NOT WORK.
#       Instead, you should do it on ./0-shared.bash

# NOTE: Implicitly loaded functions from 0-shared.bash


prepare_ios() {
	echo "Extracting .ipa file to be able to handle by ios-deploy"

	! [[ -d "$DEVFARM_AGENT_UNARCHIVED_IOS_APP_PATH" ]] || mv "$DEVFARM_AGENT_UNARCHIVED_IOS_APP_PATH" "$(mktemp -d "$DEVFARM_AGENT_UNARCHIVED_IOS_APP_PATH.old.XXXXXX")"

	local extract_dir="$(mktemp -d "/tmp/devfarmagent-extracting.XXXXXX")"
	unzip "$DEVICEFARM_APP_PATH" -d "$extract_dir"

	local app_path="$(find "$extract_dir" -name '*.app' -type d -maxdepth 2 -mindepth 2 | head -1)"
	mv "$app_path" "$DEVFARM_AGENT_UNARCHIVED_IOS_APP_PATH"

	# XXX: ios-deploy needs symbols for each version, but it not needed for our usecase.
	echo "Prepare $HOME/Library/Developer/Xcode/iOS DeviceSupport/*/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/6.1.5 (10B400)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/6.1.6 (10B500)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/7.0 (11A465)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/7.0.1 (11A470a)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/7.0.1 (11A470e)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/7.0.2 (11A501)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/7.0.2 (11A502)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/7.0.3 (11B511)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/7.0.3 (11B511d)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/7.0.4 (11B554a)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/7.0.5 (11B601)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/7.0.6 (11B651)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/7.1 (11D167)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/7.1 (11D169)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/7.1 (11D169b)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/7.1.1 (11D201)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/7.1.1 (11D201c)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/7.1.2 (11D257)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/7.1.2 (11D257c)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/7.1.2 (11D258)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/8.0 (12A365)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/8.0 (12A365b)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/8.0 (12A366)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/8.0.1 (12A402)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/8.0.2 (12A405)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/8.1 (12B410)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/8.1 (12B410a)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/8.1 (12B411)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/8.1.1 (12B435)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/8.1.1 (12B436)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/8.1.2 (12B440)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/8.1.3 (12B466)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/8.2 (12D508)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/8.3 (12F69)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/8.3 (12F70)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/8.4 (12H143)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/8.4.1 (12H321)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/8.4.1 (12H523)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/8.4.2 (12H606)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/8.4.2 (12H847)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/8.4.2 (12H864)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.0 (13A340)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.0 (13A342)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.0 (13A343)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.0 (13A344)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.0 (13T396)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.0.1 (13A404)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.0.1 (13A405)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.0.1 (13T402)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.0.2 (13A452)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.1 (13B143)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.1 (13B144)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.1 (13U85)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.1.1 (13U717)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.2 (13C75)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.2 (13Y234)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.2.1 (13D15)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.2.1 (13D20)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.2.1 (13Y772)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.2.2 (13Y825)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.3 (13E233)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.3 (13E234)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.3 (13E236)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.3 (13E237)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.3.1 (13E238)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.3.2 (13F69)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.3.2 (13F72)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.3.3 (13G34)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.3.4 (13G35)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.3.5 (13G36)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/9.3.6 (13G37)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/10.0 (14T330)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/10.0.1 (14A403)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/10.0.1 (14U100)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/10.0.1 (14U71)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/10.0.2 (14A456)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/10.0.3 (14A551)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/10.1 (14B72)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/10.1 (14B72c)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/10.1 (14U593)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/10.1.1 (14B100)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/10.1.1 (14B150)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/10.1.1 (14U712a)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/10.2 (14C92)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/10.2 (14W265)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/10.2.1 (14D27)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/10.2.1 (14W585a)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/10.2.2 (14W756)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/10.3 (14E277)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/10.3.1 (14E304)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/10.3.2 (14F8089)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/10.3.2 (14F89)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/10.3.2 (14F90)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/10.3.2 (14F91)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/10.3.3 (14G60)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/10.3.4 (14G61)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.0 (15A372)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.0 (15J381)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.0.1 (15A402)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.0.1 (15A403)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.0.2 (15A421)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.0.3 (15A432)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.1 (15B101)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.1 (15B93)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.1 (15J582)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.1.1 (15B150)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.1.2 (15B202)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.2 (15C114)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.2 (15K106)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.2.1 (15C153)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.2.1 (15K152)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.2.2 (15C202)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.2.5 (15D60)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.2.5 (15K552)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.2.6 (15D100)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.2.6 (15K600)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.3 (15E216)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.3 (15E218)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.3 (15L211)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.3.1 (15E302)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.4 (15F79)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.4 (15L577)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.4.1 (15G77)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/11.4.1 (15M73)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.0 (16A366)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.0 (16J364)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.0.1 (16A404)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.0.1 (16A405)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.0.1 (16J380)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.1 (16B92)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.1 (16B93)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.1 (16B94)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.1 (16J602)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.1.1 (16C50)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.1.1 (16K45)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.1.2 (16C101)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.1.2 (16C104)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.1.2 (16K534)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.1.3 (16D39)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.1.3 (16D40)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.1.4 (16D57)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.2 (16E227)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.2 (16L226)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.2.1 (16L250)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.3 (16F156)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.3 (16M153)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.3.1 (16F203)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.3.1 (16F8202)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.3.2 (16F250)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.4 (16G77)/Symbols"
	mkdir -p "$HOME/Library/Developer/Xcode/iOS DeviceSupport/12.4 (16M568)/Symbols"
	ls -l "$HOME/Library/Developer/Xcode/iOS DeviceSupport"
}


prepare_android() {
	echo "Do nothing."
}

        
case "$DEVICEFARM_DEVICE_PLATFORM_NAME" in
	"iOS")
		echo "Prepare dependencies for iOS"
		prepare_ios
		;;

	"Android")
		echo "Prepare dependencies for Android"
		prepare_android
		;;

	*)
		throw "unsupported platform: $DEVICEFARM_DEVICE_PLATFORM_NAME"
		;;
esac
