version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.14
    steps:
      - run:
          name: Install dependencies
          command: |
            go env
            go get -u github.com/go-bindata/go-bindata/go-bindata
      - checkout
      - run:
          name: Build assets
          command: go generate ./...
      - run:
          name: Test
          command: ./test/test-all.bash

  go_get:
    docker:
      - image: cimg/go:1.14
    steps:
      - run:
          name: Install devfarm
          command: go get github.com/DeNA/devfarm/cmd/devfarm
      - run:
          name: Test
          command: devfarm version

workflows:
  version: 2
  build:
    jobs:
      - build
      - go_get:
          filters:
            branches:
              only: master
