#!/bin/bash
set -euo pipefail

BASE_DIR="$(cd "$(git rev-parse --show-toplevel)"; pwd)"

devfarm() {
	go run ./cmd/devfarm/main.go "$@"
}

should_success() {
	echo "\$ $@"
	"$@"
	echo
}

should_fail() {
	echo "\$ $@"
	"$@" || true
	echo
}

(cd "$BASE_DIR"
	echo '```console'

	planfile="$(mktemp -d '/tmp/devfarm-init.XXXXXX')/planfile.yml"

	should_fail devfarm init --help
	should_success devfarm init "$planfile"
	should_success cat "$planfile"

	echo '```'
)
