#!/bin/bash
set -euo pipefail

BASE_DIR="$(cd "$(git rev-parse --show-toplevel)"; pwd)"
ASSUMED_GOROOT_BIN="$(go env GOROOT)/bin"

NO_AWS_PATH="${ASSUMED_GOROOT_BIN}:/bin:/usr/bin"
FAKE_AWS_BIN="${BASE_DIR}/test/usage/fake_PATH/for_aws_cli"
FAKE_AWS_PATH="${FAKE_AWS_BIN}:${NO_AWS_PATH}"

devfarm() {
	go run ./cmd/devfarm/main.go "$@"
}

run() {
	echo "\$ $@"
	"$@" || true
	echo
}

should_success() {
	echo "\$ $@"
	"$@"
	echo
}

should_fail() {
	echo "\$ $@"
	"$@" && false || true
	echo
}

(cd "$BASE_DIR"
	echo '```console'

	should_fail devfarm list-devices --help
	should_success devfarm list-devices --verbose --dry-run

	(export PATH="$NO_AWS_PATH"
		should_fail which aws
		should_success devfarm list-devices
	)

	(export PATH="$FAKE_AWS_PATH"
		should_success which aws
		should_success devfarm list-devices
	)

	echo '```'
)
