#!/bin/bash
set -euo pipefail

BASE_DIR="$(cd "$(git rev-parse --show-toplevel)"; pwd)"
ASSUMED_GOROOT_BIN="$(go env GOROOT)/bin"

NO_ANDROID_SDK_PATH="${ASSUMED_GOROOT_BIN}:/bin:/usr/bin"
FAKE_ANDROID_SDK_BIN="${BASE_DIR}/test/usage/fake_PATH/for_android_sdk/tools/bin:${NO_ANDROID_SDK_PATH}"

devfarm() {
	go run ./cmd/devfarm/main.go "$@"
}

should_success() {
	echo "\$ $@"
	"$@"
	echo
}

should_fail() {
	echo "\$ $@"
	"$@" || true
	echo
}

(cd "$BASE_DIR"
	echo '```console'

	should_fail devfarm ls-assets --help
	should_success devfarm ls-assets

	echo '```'
)
