#!/bin/bash
set -euo pipefail

BASE_DIR="$(cd "$(git rev-parse --show-toplevel)"; pwd)"
ASSUMED_GOROOT_BIN="$(go env GOROOT)/bin"

NO_AWS_PATH="${ASSUMED_GOROOT_BIN}:/bin:/usr/bin"
FAKE_AWS_BIN="${BASE_DIR}/test/usage/fake_PATH/for_aws_cli"
FAKE_AWS_PATH="${FAKE_AWS_BIN}:${NO_AWS_PATH}"
PLANFILE='./test/usage/assets/planfile.yml'

devfarm() {
	go run ./cmd/devfarm/main.go "$@"
}

should_success() {
	echo "\$ $@"
	"$@"
	echo
}

should_fail() {
	echo "\$ $@"
	"$@" && false || true
	echo
}

should_success_but_skipped() {
	echo "\$ $@"
	"$@" || true
	echo
}

(cd "$BASE_DIR"
	echo '```console'

	should_fail devfarm run-all --help
	should_success cat "$PLANFILE"

	should_success_but_skipped devfarm run-all --dry-run "$PLANFILE"

	echo '```'
)
