#!/bin/bash
set -euo pipefail

BASE_DIR="$(cd "$(git rev-parse --show-toplevel)"; pwd)"
ASSUMED_GOROOT_BIN="$(go env GOROOT)/bin"

VALID_PLANFILE='./test/usage/assets/planfile.yml'
INVALID_PLANFILE='./test/usage/assets/broken.yml'

devfarm() {
	go run ./cmd/devfarm/main.go "$@"
}

should_success() {
	echo "\$ $@"
	"$@"
	echo
}

should_fail() {
	echo "\$ $@"
	"$@" && false || true
	echo
}

should_success_but_skipped() {
	echo "\$ $@"
	"$@" || true
	echo
}

(cd "$BASE_DIR"
	echo '```console'

	should_fail devfarm validate --help
	should_success cat "$VALID_PLANFILE"

	should_success devfarm validate "$VALID_PLANFILE"
	should_fail devfarm validate "$INVALID_PLANFILE"
	should_success devfarm validate --verbose "$VALID_PLANFILE"

	echo '```'
)
