#!/bin/bash
set -euo pipefail

BASE_DIR="$(cd "$(git rev-parse --show-toplevel)"; pwd)"
ASSUMED_GOROOT_BIN="$(go env GOROOT)/bin"

devfarmagent() {
	go run ./cmd/devfarmagent/main.go "$@"
}

run() {
	echo "\$ $@"
	"$@" || true
	echo
}

should_success() {
	echo "\$ $@"
	"$@"
	echo
}

should_fail() {
	echo "\$ $@"
	"$@" && false || true
	echo
}

(cd "$BASE_DIR"
	echo '```console'

	should_success devfarmagent aws-device-farm args encode -ARG1 HELLODEVFARM
	should_success devfarmagent aws-device-farm args decode WyItQVJHMSIsIkhFTExPREVWRkFSTSJd

	echo '```'
)
