name: CI

on:
  workflow_dispatch:
  push:
    branches:
    - replace/ci
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-go@v5
        with:
          go-version: '1.14'

      - name: Install dependencies
        run: |
          go env
          go get -u github.com/go-bindata/go-bindata/go-bindata

#       - name: Install devfarm
#         run: |
#           go get github.com/dena/devfarm/cmd/devfarm
#           devfarm version

      - name: Build assets
        run: go generate ./...

      - name: Test
        run: ./test/test-all.bash
